### ISSUE TITLE
注册那一步的获取uid失败

### ISSUE THREAD

**Issue by limengke123** [vimplus/React-Koa-Mongodb#1]
参考你的代码，用`var counter = await Counter.findOneAndUpdate({tableName: tableName}, {$inc: { seq: 1} })`去生成注册时用户的uid，这里的counter一直返回的是null；该怎么解决

**Comment by limengke123** [comment]
![tim 20170915111834](https://user-images.githubusercontent.com/20045261/30465179-1a6a91a4-9a08-11e7-99cd-ebc38d52ee5f.png)

**Comment by Joyotang** [comment]
你有在数据库里面初始化counters表的数据吗？比如这样：

```
{
    "_id" : ObjectId("59ba1b29bdb58e4d400bbd61"),
    "tableName" : "users",
    "seq" : 1
}
```

**Comment by limengke123** [comment]
没有初始化couters表，在你的代码中哪一步初始化了这个表的数据？顺便问一下，如果我想创建一个文章的表也需要这样一个Uid，是否也能用这个counter表？
万分感谢~

**Comment by Joyotang** [comment]
@limengke123 代码里面没有初始化的步骤，你可以下载一个mongodb客户端工具（[Robomongo](https://robomongo.org/download)）管理你的数据库， 文章表同理，你可以insert两条数据，如：

```
{
    "tableName" : "users",
    "seq" : 1
}
{
    "tableName" : "articles",
    "seq" : 1
}
```

`_id`会自动生成的，其实如果用mongodb不是非必要可以直接用数据库自身生成的`_id`, 并且是唯一的，我这个`counters`表只是用来在mongodb中自己维护自增id的。

**Comment by limengke123** [comment]
嗯，周末用shell新增了users和articles的两条初始数据就能跑起来了
